"use strict";
let car = 'subaru';
console.log("Is car == 'subaru'? I predict true.");
console.log(car == 'subaru');
console.log("Is car == 'honda'? I predict false.");
console.log(car == 'honda');
console.log("Is car === 'subaru'? I predict true.");
console.log(car === 'subaru');
console.log("Is car === 'Subaru'? I predict false.");
console.log(car === 'Subaru');
console.log("Is car != 'ford'? I predict true.");
console.log(car != 'ford');
console.log("Is car != 'subaru'? I predict false.");
console.log(car != 'subaru');
console.log("Is car !== 'subaru'? I predict false.");
console.log(car !== 'subaru');
console.log("Is car.startsWith('su')? I predict true.");
console.log(car.startsWith('su'));
console.log("Is car.includes('bar')? I predict true.");
console.log(car.includes('bar'));
console.log("Is car.length > 5? I predict true.");
console.log(car.length > 5);
